### ISSUE TITLE
GET Lista de censos

### ISSUE THREAD

**Issue by PabloTinoco** [EGC-G2-Trabajo-1718/egc-censos#1]
Prioridad: Media

Desde Administración de Votaciones necesitamos la consulta API que nos proporcione la lista de todos los censos.

**Comment by migueltern** [comment]
La funcionalidad que pedís está resuelta en el GET /filter sin ningún parámetro, se ha añadido en la wiki para explicar con más detalle.
 https://1984.lsi.us.es/wiki-egc/index.php?title=Administraci%C3%B3n_de_censos_-_17_18_-_G2

**Comment by migueltern** [comment]
La funcionalidad que pedís está resuelta en el GET /filter sin ningún parámetro, se ha añadido en la wiki para explicar con más detalle. https://1984.lsi.us.es/wiki-egc/index.php?title=Administraci%C3%B3n_de_censos_-_17_18_-_G2
