### ISSUE TITLE
Formato json sin especificar en la url

### ISSUE THREAD

**Issue by migueltern** [EGC-G2-Trabajo-1718/egc-censos#2]
Prioridad: alta.
Estado: pendiente.
Descripción: Modificar el formato del serializer para que el Json sea devuelto sin especificar en la url.

**Comment by fjgparrales95** [comment]
Ajustes editados con éxito. Se ha cambiado el settings.py y ya devuelve en formato JSON sin problema alguno y sin necesidad de especificar más parámetros en la url.
Commit que lo arregla: 65bf9c9762091
