### ISSUE TITLE
Gestionar autenticación externa

### ISSUE THREAD

**Issue by migueltern** [EGC-G2-Trabajo-1718/egc-censos#3]
Prioridad: medio
Estado: pendiente.
Descripción: Mediante un parámetro en la URL te puedas autenticar en el censo.

**Comment by fjgparrales95** [comment]
Actualización de estado:
En progreso. Analizando y estudiando opciones: JWT, OAuth, django-auth, api-auth, y diversas librerías para una conexión autenticada simple a través de una sola petición a la api.
