### ISSUE TITLE
Obtención de los usuarios que pertenezcan a un censo

### ISSUE THREAD

**Issue by NachoAlesLopez** [EGC-G2-Trabajo-1718/egc-censos#4]
Desde cabina de votaciones, necesitamos conocer si un usuario tiene posibilidad de votar y debemos comprobar si un usuario, que se pasaría su id, pertenece al censo de la votación, que podemos pasar o bien el id de la votación, el id del censo o ningúno y que se devuelva el censo en sí o un mensaje de error si no pertenece al censo.

**Comment by migueltern** [comment]
Dichas funcionalidades ya están resueltas, con la url can_vote,le dejo un enlace a la wiki [aquí](https://1984.lsi.us.es/wiki-egc/index.php?title=Administraci%C3%B3n_de_censos_-_17_18_-_G2). Si que nos faltaría desplegar la aplicación.

**Comment by NachoAlesLopez** [comment]
En efecto, la funcionalidad está, no la había visto en la wiki. Gracias y perdón por las molestias.
